nome = input ("Digite seu nome: ")
rua = input ("qual o nome da sua rua? ")
n = input ("e qual o número da sua casa? ")
bairro = input ("agora me diga em qual bairro você mora: ")
cidade = input ("Em que cidade fica seu endereco? ")
uf = input ("Em qual estado fica essa cidade? ")
cep= input ("Digite seu CEP: ")
print (nome, "você mora na rua", rua,"nrº",n, "- bairro", bairro, "em", cidade, "no estado do", uf, "e seu CEP é ", cep)
